more work on kagui

diff --git a/kagui b/kagui
--- a/kagui
+++ b/kagui
@@ -5,93 +5,127 @@ appname="Kagui"
 
 errors=0
 # Require kdialog
-[ -f "$(which kdialog 2>/dev/null)" ] || {
+if [ ! -f "$(which kdialog 2>/dev/null)" ]; then
 	echo "ERROR: $appname requires kdialog to run; please install it and try again."
 	let errors++
-}
+fi
 
 # Require apk (obviously)
-[ -f "$(which apk 2>/dev/null)" ] || {
+if [ ! -f "$(which apk 2>/dev/null)" ]; then
 	echo "ERROR: $appname requires apk to run; please install it and try again."
 	let errors++
-}
+fi
 
-[ $errors -ne 0 ] && {
+if [ $errors -ne 0 ]; then
 	echo "Exiting with $errors fatal errors."
 	exit 1
-}
+fi
+
+err_file="/tmp/${appname}_err"
+sudo_passwd=""
 
 main_menu() {
+	if [ -f "$err_file" ]; then
+		rm "$err_file"
+	fi
 	opt="$(kdialog --title "$appname" --menu "Welcome to $appname.  Select an option below" \
 		"add" "Search / install packages" \
 		"del" "Search / remove installed packages" \
 		"exit" "Exit")"
 	case "$opt" in
-		"add") install ;;
-		"del") uninstall ;;
+		"add") un_install "add" ;;
+		"del") un_install "del" ;;
 		"exit") exit 0 ;;
 		"") exit 0 ;;
 		*) echo "$opt not implemented"
 	esac
 }
 
-install() {
+un_install() {
+    # Call with "add" for install, "del" for uninstall
+	
+    if [ "$1" = "add" ]; then
+		apk_cmd="apk add --no-progress"
+		search_cmd="apk search -q"
+		title="Install"
+		prog_msg="Installing..."
+	elif [ "$1" = "del" ]; then
+		apk_cmd="apk del"
+		search_cmd="apk info"
+		title="Uninstall"
+		prog_msg="Uninstalling..."
+	else
+		echo "Bad argument $1"
+		return 1
+	fi
+	
 	search_term="$(search_dialog)"
-	packages="$(kdialog --title "$appname > Install" --checklist "Choose package(s):" \
-		$(apk search -q | grep "$search_term" | awk '{print $1, $1, "off"}') | sed 's/"//g')"
+	if [ "$?" -eq 1]; then
+		return 1
+	fi
+	packages="$(kdialog --title "$appname > $title" --checklist "Choose package(s):" \
+		$($search_cmd | grep "$search_term" | awk '{print $1, $1, "off"}') | sed 's/"//g')"
+	if [ -z "$packages" ]; then
+		return 1
+	fi
 	passwd="$(get_passwd)"
-	echo "$passwd" | sudo -S apk add --no-progress $packages 2>/tmp/kagui_err | track_progress "Installing..."
-	kagui_err="$(cat /tmp/kagui_err 2>/dev/null)"
-	[ -z "$kagui_err" ] || {
-		kdialog --title "$appname > Error" --textbox /tmp/kagui_err
-	return 1
-	}
-	main_menu
+	echo "$passwd" | sudo -S $apk_cmd $packages 2>"$err_file" | track_progress "$prog_msg"
+	_err="$(cat "$err_file" 2>/dev/null)"
+	if [ ! -z "$_err" ]; then
+		kdialog --title "$appname > Error" --textinputbox "apk returned error with following output:" "$_err"
+		return 1
+	fi
+	return 0
 }
-
-uninstall() {
-	search_term="$(search_dialog)"
-	packages="$(kdialog --title "$appname > Uninstall" --checklist "Choose package(s):" \
-		$(apk info -q | grep "$search_term" | awk '{print $1, $1, "off"}') | sed 's/"//g')"
-	passwd="$(get_passwd)"
-	echo "$passwd" | sudo -S apk del $packages 2>/tmp/kagui_err | track_progress "Uninstalling..."
-	kagui_err="$(cat /tmp/kagui_err 2>/dev/null)"
-	[ -z "$kagui_err" ] || {
-		kdialog --title "$appname > Error" --textbox /tmp/kagui_err
-	return 1
-	}
-	main_menu
-}
-
 
 search_dialog() {
 	# Generic function to get search term from user and output it to stdout
 	search_term="$(kdialog --title "$appname > Search" --inputbox "Enter search term (blank to return all)")"
-	[ "$?" -eq 0 ] && echo "$search_term" || main_menu
+	if [ "$?" -eq 0 ]; then
+		echo "$search_term"
+		return 0
+	else
+		return 1
+	fi
 }
 
 get_passwd() {
-	[ -z "$sudo_passwd" ] && sudo_passwd="$(kdialog --title "$appname > Enter password" --password "Enter your password for sudo.")"
+	if [ -z "$sudo_passwd" ]; then
+		sudo_passwd="$(kdialog --title "$appname > Enter password" --password "Enter your password for sudo.")"
+	fi
 	echo "$sudo_passwd"
 }
 
 track_progress() {
-	tracker="$(kdialog --progressbar "$1" 100)"
+	#tracker="$(kdialog --progressbar "$1" 100)"
 	while STATUS= read -r line; do
-		kagui_err="$(cat /tmp/kagui_err 2>/dev/null)"
-		[ -z "$kagui_err" ] || {
-			#kdialog --title "$appname > Error" --textbox /tmp/kagui_err
-			#return 1
-			echo "$line" >> /tmp/kagui_err
+		_err="$(cat "$err_file" 2>/dev/null)"
+		if [ -z "$_err" ]; then
+			# No errors found
+			step_number="$(echo "$line" | grep -o "^([[:digit:]]\+/[[:digit:]]\+)")"
+			if [ ! -z "$step_number" ]; then
+				# Line begining with (X/YY) found, indicating that progress is being made
+				# (eg, package is being downloaded or deleted)
+				if [ -z "$tracker" ]; then
+					tracker="$(kdialog --progressbar "$1" 100)"
+				fi
+				qdbus $tracker Set "" value "$(echo "$step_number*100" | bc -l | awk -F "." '{print $1}')"
+			fi
+			if [ ! -z "$tracker" ]; then
+				qdbus $tracker setLabelText "$line"
+			fi
+		else
+			# Errors found
+			echo "$line" >> "$err_file"
 			continue
-		}
-		step_number="$(echo "$line" | grep -o "^([[:digit:]]\+/[[:digit:]]\+)")"
-		[ -z "$step_number" ] || qdbus $tracker Set "" value "$(echo "$step_number*100" | bc -l | awk -F "." '{print $1}')"
-		qdbus $tracker setLabelText "$line"
-		#echo "$line" | grep '^\[\d{1,3}'
+		fi
 	done
-	qdbus $tracker close
+	if [ ! -z "$tracker" ]; then
+		qdbus $tracker close
+	fi
 	return 0
 }
 
-main_menu
+while true; do
+	main_menu
+done
